Source Code/plugins/UserManager/src/Model/Entity/User.php
<?php
declare(strict_types=1);

namespace UserManager\Model\Entity;

use Cake\ORM\Entity;
use CakeDC\Users\Model\Entity\User as CakeDCUser;

/**
 * User Entity
 *
 * @property string $id
 * @property string $username
 * @property string|null $email
 * @property string $password
 * @property string|null $first_name
 * @property string|null $last_name
 * @property string|null $token
 * @property \Cake\I18n\FrozenTime|null $token_expires
 * @property string|null $api_token
 * @property \Cake\I18n\FrozenTime|null $activation_date
 * @property string|null $secret
 * @property bool|null $secret_verified
 * @property \Cake\I18n\FrozenTime|null $tos_date
 * @property bool $active
 * @property bool $is_superuser
 * @property string|null $role
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 * @property string|null $additional_data
 *
 * @property \UserManager\Model\Entity\SocialAccount[] $social_accounts
 * @property \UserManager\Model\Entity\UserToken[] $user_tokens
 */
class User extends CakeDCUser
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'listing_id' => true,
        'code' => true,
        'username' => true,
        'email' => true,
        'zoom_email' => true,
        'password' => true,
        'first_name' => true,
        'last_name' => true,
        'token' => true,
        'token_expires' => true,
        'api_token' => true,
        'activation_date' => true,
        'secret' => true,
        'secret_verified' => true,
        'tos_date' => true,
        'active' => true,
        'is_superuser' => true,
        'role' => true,
        'profile_photo' => true,
        'photo_dir' => true,
        'photo_size' => true,
        'photo_type' => true,
        'comment' => true,
        'created' => true,
        'modified' => true,
        'additional_data' => true,
        'social_accounts' => true,
        'user_tokens' => true,
        'user_profiles' => true,
        'user_profile' => true,
        'referred_by' => true,
        'teacher_schedules' => true,
        'grading_types' => true,
        'boards' => true,
        'transactions' => true,
        'user_documents' => true,
        'languages' => true
    ];

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password',
        'token',
    ];
    /**
     * Fields that will be add in JSON response.
     *
     * @var array
     */
    protected $_virtual = ['name', 'image_path'];

    /**
     * Get the full name.
     *
     * @param  string  $value
     * @return string
     */
    protected function _getName()
    {
        $name[] = $this->first_name;
        $name[] = $this->last_name;
        return implode(" ", array_filter($name));
    }

    protected function _getImagePath()
    { 
        if(isset($this->photo_dir)){
            return str_replace("\\", "/", str_replace("webroot\img\\","", str_replace("webroot/img/","",$this->photo_dir)));
        }
    }
    
}

Source Code/plugins/UserManager/src/Model/Table/UserProfilesTable.php
<?php
declare(strict_types=1);

namespace UserManager\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\ORM\TableRegistry;
use Cake\Event\Event;
use App\MobileSms;
use Cake\Event\EventInterface;
use Cake\Datasource\EntityInterface;
use ArrayObject;

/**
 * UserProfiles Model
 *
 * @property \UserManager\Model\Table\UsersTable&\Cake\ORM\Association\BelongsTo $Users
 * @property \UserManager\Model\Table\LocationsTable&\Cake\ORM\Association\BelongsTo $Locations
 * @property \UserManager\Model\Table\OccupationsTable&\Cake\ORM\Association\BelongsTo $Occupations
 * @property \UserManager\Model\Table\PrimarySubjectsTable&\Cake\ORM\Association\BelongsTo $PrimarySubjects
 * @property \UserManager\Model\Table\SecondarySubjectsTable&\Cake\ORM\Association\BelongsTo $SecondarySubjects
 *
 * @method \UserManager\Model\Entity\UserProfile newEmptyEntity()
 * @method \UserManager\Model\Entity\UserProfile newEntity(array $data, array $options = [])
 * @method \UserManager\Model\Entity\UserProfile[] newEntities(array $data, array $options = [])
 * @method \UserManager\Model\Entity\UserProfile get($primaryKey, $options = [])
 * @method \UserManager\Model\Entity\UserProfile findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \UserManager\Model\Entity\UserProfile patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \UserManager\Model\Entity\UserProfile[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \UserManager\Model\Entity\UserProfile|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \UserManager\Model\Entity\UserProfile saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \UserManager\Model\Entity\UserProfile[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \UserManager\Model\Entity\UserProfile[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \UserManager\Model\Entity\UserProfile[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \UserManager\Model\Entity\UserProfile[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class UserProfilesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);
        $this->_dir = 'webroot' . DS . 'img' . DS . 'uploads' . DS;

        $this->setTable('user_profiles');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER',
            'className' => 'UserManager.Users',
        ]);
        $this->belongsTo('Locations', [
            'foreignKey' => 'location_id',
            'joinType' => 'LEFT',
            'className' => 'Locations.Locations',
        ]);

        $this->belongsTo('GradingTypes', [
            'foreignKey' => 'grading_type_id',
            'joinType' => 'LEFT',
            'className' => 'Courses.GradingTypes',
        ]);

        $this->belongsTo('Occupations', [
            'foreignKey' => 'occupation_id',
            'className' => 'UserManager.Occupations',
        ]);
        $this->belongsTo('PrimarySubjects', [
            'foreignKey' => 'primary_subject_id',
            'className' => 'Courses.Subjects',
        ]);
        $this->belongsTo('SecondarySubjects', [
            'foreignKey' => 'secondary_subject_id',
            'className' => 'Courses.Subjects',
        ]);

        $this->addBehavior('Josegonzalez/Upload.Upload', [
            'resume' => [
                'fields' => [
                    // if these fields or their defaults exist
                    // the values will be set.
                    'dir' => 'resume_dir', // defaults to `dir`
                    'size' => 'resume_size', // defaults to `size`
                    'type' => 'resume_type', // defaults to `type`
                ],
                'nameCallback' => function ($table, $entity, $data, $field, $settings) {
                        $ext = pathinfo($data->getClientFilename(), PATHINFO_EXTENSION);
                        return rand(100000,999999).time().rand(10000 , 99999).".".$ext;
                        //return strtolower(str_replace(" ","",$data['name']));
                },
                'path' => $this->_dir.'{model}{DS}{field}{DS}',
                'keepFilesOnDelete' => false
            ],
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {

        $validator->setProvider('upload', \Josegonzalez\Upload\Validation\UploadValidation::class);
        $validator->setProvider('upload', \Josegonzalez\Upload\Validation\ImageValidation::class);
        $validator->setProvider('upload', \Josegonzalez\Upload\Validation\DefaultValidation::class);

        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->notEmptyString('mobile', 'Mobile number is required')
            ->add('mobile', [
                'maxLength' => [
                    'rule' => ['maxLength', 14],
                    'message' => 'Mobile number is too long. The limit is 14 characters.'
                ],
                'minLength' => [
                    'rule' => ['minLength', 10],
                    'message' => 'Mobile number is short. The min limit is 10 characters.'
                ],
                'custom' => [
                    'rule' => ['numeric'],
                    'on' => function($context) {
                    return !empty($context['data']['mobile']);
                },
                    'message' => 'Invalid mobile number! mobile number format: eg 10-14.'
                ]
        ]); 

        $validator
            ->scalar('alt_mobile')
            ->maxLength('alt_mobile', 20)
            ->allowEmptyString('alt_mobile');

        $validator
            ->date('dob')
            ->notEmptyDate('dob', 'Date of birth cannot be left empty');

        $validator
            ->scalar('address_line_1')
            ->maxLength('address_line_1', 150)
            ->allowEmptyString('address_line_1');

        $validator
            ->scalar('address_line_2')
            ->maxLength('address_line_2', 150)
            ->allowEmptyString('address_line_2');

        $validator
            ->scalar('postcode')
            ->maxLength('postcode', 8)
            ->allowEmptyString('postcode');

        $validator
            ->scalar('gender')
            ->maxLength('gender', 10)
            ->allowEmptyString('gender');

        $validator
            ->scalar('qualification')
            ->maxLength('qualification', 250)
            ->notEmptyString('qualification');

        $validator
            ->scalar('college_university')
            ->maxLength('college_university', 250)
            ->notEmptyString('college_university');

        $validator
            ->scalar('experience')
            ->maxLength('experience', 50)
            ->notEmptyString('experience');

        $validator
            ->scalar('hours_inweekdays')
            ->maxLength('hours_inweekdays', 255)
            ->notEmptyString('hours_inweekdays');

        $validator
            ->scalar('hours_inweekend')
            ->maxLength('hours_inweekend', 255)
            ->notEmptyString('hours_inweekend');

        $validator
            ->boolean('is_digital_pen_tablet')
            ->allowEmptyString('is_digital_pen_tablet');

        $validator
            ->boolean('is_internet_speed_mbps')
            ->allowEmptyString('is_internet_speed_mbps');

        $validator
            ->scalar('source_of_rudraa')
            ->maxLength('source_of_rudraa', 255)
            ->notEmptyString('source_of_rudraa');

        // $validator
        //    ->maxLength('resume', 255)
        //    ->notEmptyFile('resume', 'Resume document is required');

        $validator
        //->allowEmptyString('resume', 'update')
        ->add('resume', 'customName', [
            'rule' => 'isFileUpload',
            'message' => 'Resume document is required',
            'provider' => 'upload',
            'on' => function($context) {
                return $context['newRecord'];
                // return !empty($context['data']['resume']) && $context['data']['resume']->getError() == UPLOAD_ERR_OK;
            }
        ]);

        $validator->add('resume', 'file', [
                'rule' => ['mimeType', ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.oasis.opendocument.text']],
                'on' => function ($context) {
                    //dd($context['data']['resume']);
                    return !empty($context['data']['resume']) && $context['data']['resume']->getError() == UPLOAD_ERR_OK;
                },
                'message' => 'Resume document is not valid! please use valid format e.g PDF, DOC, DOCX',
                'last' => true,
            ]);


        $validator
            ->allowEmptyFile('profile_photo');

        $validator
            ->scalar('about_me')
            ->allowEmptyString('about_me');

        $validator
            ->scalar('achievement')
            ->maxLength('achievement', 255)
            ->allowEmptyString('achievement');

        $validator
            ->scalar('other_achievement')

Source Code/plugins/UserManager/templates/Users/assistant.php
<?php
//$this->layout = "authdefault";
/**
 * Copyright 2010 - 2019, Cake Development Corporation (https://www.cakedc.com)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright 2010 - 2018, Cake Development Corporation (https://www.cakedc.com)
 * @license MIT License (http://www.opensource.org/licenses/mit-license.php)
 */
?>
<div class="SLoginArea">
        <div class="container">
            <div class="col-md-12">
                <div class="col-md-8 col-md-offset-2 FTStep">
                    <div class="col-md-12 nopadding">
                        <div class="col-md-3">
                            <?= $this->Html->image('RudraaBot.jpg') ?>
                        </div>
                        <div class="col-md-9">
                            <h2>Hey this is <span>OMM</span>,</h2>
                            <h3>Your Personal Virtual Assistant</h3>
                            <p><span>I'll help you to find the best teacher for you !</span></p>
                        </div>
                        <div class="col-md-12 bottom">
                            <div class="col-md-12 text-center">
                                <?= $this->Html->link("Lets get Start", ['controller' => 'Users', 'action' => 'assistant', 'plugin' => 'UserManager', '?' => ['step' => 'grade']], ['class' => 'nxtbtn']) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php
$this->assign('title', "Virtual Assistant");
$this->Html->meta(
    'keywords', 'Virtual Assistant', ['block' => true]
);
$this->Html->meta(
    'description', 'Virtual Assistant', ['block' => true]
);

//$this->Html->css(['/assets/plugins/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min'], ['block' => true]);
//$this->Html->script(['/assets/plugins/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.min'], ['block' => true])//;
?> 

Source Code/plugins/UserManager/templates/Users/assistant_subject.php
<?php
//$this->layout = "authdefault";
/**
 * Copyright 2010 - 2019, Cake Development Corporation (https://www.cakedc.com)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright 2010 - 2018, Cake Development Corporation (https://www.cakedc.com)
 * @license MIT License (http://www.opensource.org/licenses/mit-license.php)
 */
?>
<div class="SLoginArea">
        <div class="container">
            <div class="col-md-12">
                <div class="col-md-8 col-md-offset-2 FTStep">
                    <div class="col-md-10 col-md-offset-1 nopadding">
                        <div class="col-md-12">
                            <div class="col-md-2">
                                <?= $this->Html->image('RudraaAssistant.gif') ?>
                            </div>
                            <div class="col-md-10">
                                <h2>Select a Subject You want to Learn.</h2>
                            </div>
                        </div>
                        <div class="col-md-12 select mySubject">
                            <div class="col-md-12">
                                <h3>Subjects</h3>
                                <?php foreach($subjects as $sid => $subject){ ?>
                                    <a href="javascript:void(0)" data-board="<?= $sid ?>" class="tag<?php echo $this->request->getQuery('subjects') && in_array($sid, $this->request->getQuery('subjects')) ? " active" : "" ?>"><?= $subject ?></a>
                                <?php } ?>
                            </div>
                        </div>
                    </div>

                     <div class="col-md-12 bottom">
                        <?= $this->Form->create(null, ['url' => ['controller' => 'Users', 'action' => 'assistant', 'plugin' => 'UserManager'], 'role' => 'form', 'enctype' => 'multipart/form-data', 'type' => 'get','valueSources' => ['query', 'context'], 'id' => 'assistantForm']) ?>
                        <div class="" style="display: none;">
                        <?php
                                echo $this->Form->input("step", ['type' => 'hidden', 'value' => 'learn']);
                                echo $this->Form->select('subjects', $subjects, ['multiple' => 'checkbox']);
                                echo $this->Form->select('grading_types', $gradingTypes, ['multiple' => 'checkbox']);
                                echo $this->Form->select('boards', $boards, ['multiple' => 'checkbox']);
                            //$this->Form->input("board.", ['type' => 'hidden']);
                            //$this->Form->input("grade.", ['type' => 'hidden']) 

                                 $queryStr = $this->request->getQuery();
                                $queryStr['step'] = 'grade';
                                ?>
                        </div>
                        <div class="col-md-4 leftalign">
                            <?= $this->Html->link("<i class=\"glyphicon glyphicon-menu-left\"></i> Back", ['controller' => 'Users', 'action' => 'assistant', 'plugin' => 'UserManager', '?' => $queryStr], ['class' => 'backbtn', 'escape' => false]) ?>
                        </div>
                        <div class="col-md-4 centeralign">
                            <a class="nobtn">Step : 2 / 3</a>
                        </div>
                        <div class="col-md-4 rightalign">
                            <?= $this->Form->button("Next <i class=\"glyphicon glyphicon-menu-right\"></i>", ['class' => 'btn btn-success', 'escapeTitle' => false]) ?>
                        </div>
                        <?= $this->Form->end() ?>
                    </div>

                    
                </div>
            </div>
        </div>
    </div>

<?php
$this->assign('title', "Select a Subject You want to Learn");
$this->Html->meta(
    'keywords', 'Select a Subject You want to Learn', ['block' => true]
);
$this->Html->meta(
    'description', 'Select a Subject You want to Learn', ['block' => true]
);

//$this->Html->css(['/assets/plugins/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min'], ['block' => true]);
//$this->Html->script(['/assets/plugins/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.min'], ['block' => true])//;
?> 

<style type="text/css">
a.active {
    background: #ed4426 !important;
    border: 1px solid #de5900 !important;
    text-decoration: none !important;
    color: #fff !important;
    transition: 0.4s;
}
</style>
 <script>
<?php $this->Html->scriptStart(['block' => true]); ?>

    
     $("#assistantForm").on("submit", function(){
        var is_board = true;
        var is_grad = true;
        if($(".mySubject a.active").length == 0){
            is_board = false;
                $.alert({
                    title: '',
                    content: 'Please choose at least one subject.',
                });
            return false;
        }
 })

    $("div.mySubject a").on("click", function(){
        var _this = $(this);
        _this.toggleClass('active');
        //_this.addClass('active');
        var subjects = [];
        $(".mySubject a.active").each(function(index, value){
            subjects.push($(this).data('board'));
        });
        $( "input[name^='subjects']" ).val(subjects);
        console.log(subjects);
    })
<?php $this->Html->scriptEnd(); ?>
</script>

Source Code/plugins/UserManager/templates/Users/croping.php
<style>
    .custom-file-control::before {
    content: "Browse";
}
.custom-file-control:empty::after {
    content: "Choose file...";
}
</style>
<div class="">
    <div class="cropping-top-sc">
        <div>
            <span>Upload a profile image with cropping option</span>
        </div>
        <div class="">
            <label class="btn btn-block btn-primary btn-lg mb-1 btn-upload" for="inputImage" title="Upload image file">
                <input type="file" class="sr-only" id="inputImage" name="file" accept="image/*">
                <span class="docs-tooltip spinloader" data-toggle="tooltip" title="" data-original-title="Import image with Blob URLs">
                    <span class="fa fa-upload"></span> Upload Profile Photo
                </span>
                </label>
        </div>
    </div>


<div class="row uploadContainer" style="">
    <div class="col-xl-10 col-lg-9">
        <div class="img-container">
            <?= $this->Html->image('no_image.gif',
                        ['id' => 'cropperImage']
                    ); ?>
         </div>
    </div>
<!-- /.Your image -->
<!-- .Croping image -->
    <div class="col-xl-2 col-lg-3">
        <div class="docs-preview clearfix">
            <span>Preview</span>
            <div class="img-preview preview-lg"></div>
        </div>
        <input type="hidden" name="image_type" class="form-control" id="uploadedImageType" value="image/jpeg">
    <!-- <h3>Data:</h3> -->
    </div>
    <div class="col-md-12">
        <hr class="mb-0">
    </div>
</div>
</div>
<!-- /.Croping functionality for image -->
<script>
    $(function () {
    var Cropper = window.Cropper;
    var URL = window.URL || window.webkitURL;
    var container = document.querySelector('.img-container');
    var image = container.getElementsByTagName('img').item(0);
    var options = {
        aspectRatio: 1 / 1,
        viewMode: 2,
        minCropBoxWidth: 200,
        minCropBoxHeight: 200,
        preview: '.img-preview',
        ready: function (e) {
        console.log(e.type);
        },
        cropstart: function (e) {
        console.log(e.type, e.detail.action);
        },
        cropmove: function (e) {
        console.log(e.type, e.detail.action);
        },
        cropend: function (e) {
        console.log(e.type, e.detail.action);
        },
        crop: function (e) {
            var data = e.detail;
        },
        zoom: function (e) {
        console.log(e.type, e.detail.ratio);
        }
  };
  cropperFx = new Cropper(image, options);
  var originalImageURL = image.src;
  var uploadedImageType = 'image/jpeg';
  var uploadedImageName = 'picture.jpg';
  var uploadedImageURL;

  var inputImage = document.getElementById('inputImage');

  if (URL) {
    inputImage.onchange = function () {

      var files = this.files;
      var file;
        console.log(files);
      if (cropperFx && files && files.length) {
        crpConfirm.buttons.crop.disable();
        var l = Ladda.create( document.querySelector( '.spinloader' ) );
        l.start();
        file = files[0];
        var a=(file.size);
        if(a > 5000000) {
            $.alert('Image size should be less than 5mb.');
            l.stop();
            return false;
        };

        if (/^image\/\w+/.test(file.type)) {
          uploadedImageType = file.type;
          uploadedImageName = file.name;
          $("#uploadedImageType").val(file.type);
          if (uploadedImageURL) {
            URL.revokeObjectURL(uploadedImageURL);
          }
          image.src = uploadedImageURL = URL.createObjectURL(file);
          l.stop();
          cropperFx.destroy();
          cropperFx = new Cropper(image, options);
          inputImage.value = null;
          //$("div.row.uploadContainer").addClass('d-block');
          crpConfirm.buttons.crop.show();
          crpConfirm.buttons.crop.enable();
        } else {
            $.alert('Please choose an image file.');
            l.stop();
          //window.alert('Please choose an image file.');
        }
      }
    };
  } else {
    inputImage.disabled = true;
    inputImage.parentNode.className += ' disabled';
  }
});
</script>

Source Code/plugins/UserManager/templates/Users/index.php
<?php
/**
 * Copyright 2010 - 2019, Cake Development Corporation (https://www.cakedc.com)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright 2010 - 2018, Cake Development Corporation (https://www.cakedc.com)
 * @license MIT License (http://www.opensource.org/licenses/mit-license.php)
 */
?>
<div class="actions columns large-2 medium-3">
    <h3><?= __d('cake_d_c/users', 'Actions') ?></h3>
    <ul class="side-nav">
        <li><?= $this->Html->link(__d('cake_d_c/users', 'New {0}', $tableAlias), ['action' => 'add']) ?></li>
    </ul>
</div>
<div class="users index large-10 medium-9 columns">
    <table cellpadding="0" cellspacing="0">
        <thead>
        <tr>
            <th><?= $this->Paginator->sort('username', __d('cake_d_c/users', 'Username')) ?></th>
            <th><?= $this->Paginator->sort('email', __d('cake_d_c/users', 'Email')) ?></th>
            <th><?= $this->Paginator->sort('first_name', __d('cake_d_c/users', 'First name')) ?></th>
            <th><?= $this->Paginator->sort('last_name', __d('cake_d_c/users', 'Last name')) ?></th>
            <th class="actions"><?= __d('cake_d_c/users', 'Actions') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach (${$tableAlias} as $user) : ?>
            <tr>
                <td><?= h($user->username) ?></td>
                <td><?= h($user->email) ?></td>
                <td><?= h($user->first_name) ?></td>
                <td><?= h($user->last_name) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__d('cake_d_c/users', 'View'), ['action' => 'view', $user->id]) ?>
                    <?= $this->Html->link(__d('cake_d_c/users', 'Change password'), ['action' => 'changePassword', $user->id]) ?>
                    <?= $this->Html->link(__d('cake_d_c/users', 'Edit'), ['action' => 'edit', $user->id]) ?>
                    <?= $this->Form->postLink(__d('cake_d_c/users', 'Delete'), ['action' => 'delete', $user->id], ['confirm' => __d('cake_d_c/users', 'Are you sure you want to delete # {0}?', $user->id)]) ?>
                </td>
            </tr>

        <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->prev('< ' . __d('cake_d_c/users', 'previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__d('cake_d_c/users', 'next') . ' >') ?>
        </ul>
        <p><?= $this->Paginator->counter() ?></p>
    </div>
</div>

Source Code/plugins/UserManager/templates/Users/load_teachers.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \Cake\Datasource\EntityInterface[]|\Cake\Collection\CollectionInterface $users
 */
$this->layout = "ajax";
?>
<?php if (!empty($users->toArray())):
        $i = ((($this->Paginator->param('page') - 1) * $this->Paginator->param('perPage')) + 1);
    foreach ($users as $user): 
        $avg = $user->avg_rating ? $user->avg_rating : 0;
        //dump($user);
        ?>
        <div class="col-sm-12 teacher-box-listview">
                <table>
                    <tr>
                        <td class="text-center">
                            <?php 
                                if (!empty($user->image_path) && !empty($user->profile_photo) && file_exists("img/".$user->image_path . $user->profile_photo)) { 
                                        $userPhoto = $user->image_path . $user->profile_photo;
                                    }else{
                                        $userPhoto = \Cake\Core\Configure::read('Users.Avatar.placeholder');
                                    }
                               echo $this->Html->image($userPhoto, ['width' => '100']);
                            ?>
                           <!--  <h6 class="green-color"><i class="glyphicon glyphicon-stop"></i> Online</h6> -->
                        </td>
                        <td>
                            <h3><?= $user->name ?></h3>
                            <p><?= $user->user_profile->qualification ?? "" ?>, <?= $user->user_profile->college_university ?? "" ?></p>
                            <p>Teaches - <?= $user->user_profile->primary_subject->title ?? "" ?> <?= isset($user->user_profile->secondary_subject) ? ", ". $user->user_profile->secondary_subject->title : "" ?></p>
                        </td>
                        <td>
                            <h4>
                                <?php for($s = 1; $s <= 5; $s++){
                                    if($s <= round($avg)){
                                        echo '<i class="fas fa-star"></i>';
                                    }else{
                                        echo '<i class="far fa-star" style=""></i>';
                                    }
                                } ?>
                                <!-- <i class="fa fa-star"></i> 
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-half mr-5"></i> -->
                                <?= round($avg,1) ?>
                            </h4>
                            <h5>Teaching Experience : <?= $user->user_profile->experience ?? 0 ?><?php echo !empty($user->user_profile->experience_month) ? "." . $user->user_profile->experience_month : "" ?> Year(s)</h5>
                            <!-- <a href="TeacherProfile.html" class="tb-btn-md mt10">Profile</a> -->
                             <?= $this->Html->link("Profile <i class=\"glyphicon glyphicon-menu-right\"></i>", ['controller' => 'Users', 'action' => 'profile', 'plugin' => 'UserManager', $user->id], ['class' => 'tb-btn-md mt10', 'escape' => false]) ?>
                        </td>
                    </tr>
                </table>
            </div>
<?php $i++; endforeach; ?>
<?php else: ?>
        <div style="text-align:center;">
            <strong>Record Not Available</strong>  
        </div>
<?php endif; ?>